# Originally duplicated from UW Visualization Curriculum
# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: UC Irvine Math 10, Fall 2023
author: Yutong Sha
copyright: "2023"
#logo: images/digitsyellow.png

# See https://jupyterbook.org/content/execute.html
execute:
  exclude_patterns:
    - 'Week?/*.ipynb'
    - 'Week??/*.ipynb'
    #- 'Proj/StudentProjects/*.ipynb'
  execute_notebooks: 'cache'
  allow_errors: true
  timeout: 200


#launch_buttons:
#  colab_url: "https://colab.research.google.com"

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/yutongo/UCI_MATH10_F23 # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
  #favicon : "images/favicon.ico"

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_extra_path:
      - data
      - extra
      - .github
